version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: springonetomany   # Database name matches Spring Boot config
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d   # Optional SQL scripts
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - akpsnetwork

  player-team-cucumber:
    build:
      context: ./       # Dockerfile location
      dockerfile: Dockerfile
    container_name: player-team-cucumber-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/springonetomany
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "7074:8080"
    restart: on-failure
    volumes:
      - ./data/compose-app:/app
    networks:
      - akpsnetwork

networks:
  akpsnetwork:
    external: true

volumes:
  mysqldata: